### ISSUE TITLE
NameError: name 'DeformConv' is not defined

### ISSUE THREAD

**Issue by ZhangYu1ing** [abhigoku10/GoogleColab#1]
Hi,

I am also using Colab to train CenterPoint. However, when I used Python3 to run the train.py, it returned the **NameError: 'DeformConv' is not defined**. If I ran the dist_test.py instead of train.py, it returned back the **ImportError: cannot import name 'deform_conv_cuda' from 'det3d.ops.dcn'**.

Did you meet the same problem when used Colab to run train the model?

Thanks in advance.😬
<img width="1177" alt="Screen Shot 2021-03-17 at 5 06 58 PM" src="https://user-images.githubusercontent.com/37301722/111499395-306de880-8743-11eb-98c8-70ab1b23ad8c.png">
<img width="1212" alt="Screen Shot 2021-03-17 at 5 09 01 PM" src="https://user-images.githubusercontent.com/37301722/111499677-79be3800-8743-11eb-81c1-930d1592c5f1.png">

**Comment by abhigoku10** [comment]
@ZhangYu1ing  yes i had ran into this issue you need ot export the path of the det3d or using sys.path.append () , just check which is ur current directory ,if ur current directory is the root of the centerpoint then sometimes u end up with this issue

**Comment by ZhangYu1ing** [comment]
Hi,

I have exported the path of det3d, det3d/ops/dcn and det3d/ops/iou3d_nms. However, it still has the same problem as before. You said that if my current director was centerpoint, it might cause this problem. So what is your directory of root when you either run train.py or dist_test.py?

Thanks a lot.

**Comment by abhigoku10** [comment]
@ZhangYu1ing  please check if this line gets executed 
![image](https://user-images.githubusercontent.com/22094053/111607410-396fc000-87fe-11eb-82bd-d3e5910526da.png)
if not then you have go two to 3steps back

**Comment by ZhangYu1ing** [comment]
Hi, 

when you run the setup.py in CenterPoint/det3d/ops/dcn, does it create any files or folders in dcn/build/temp.linux-x86_64-3.7/src ? Since now I am in this step:
<img width="757" alt="Screen Shot 2021-03-18 at 2 06 02 PM" src="https://user-images.githubusercontent.com/37301722/111630860-14c21b00-87f3-11eb-8c64-0cbc21c6833f.png">

and it returns the **error: command 'x86_64-linux-gnu-gcc' failed with exit status 1**, therefore, I am wondering whether you could successfully build something or not. If you did build something, perhaps either I missed something or our versions for torch, cuda, torchvision are not totally same.
